recall_five/first_recall/urls.py
from django.urls import path,include
from first_recall import views

app_name='first_recall'

urlpatterns=[
path('register/',views.register,name="register"),
path('login/',views.user_login,name="user_login")
]

recall_five/recall_five/urls.py
from django.contrib import admin
from django.urls import path,include
from first_recall import views

urlpatterns = [
    path('polls/',views.index,name="polls"),
    path('info/',views.info,name='info'),
    path('admin/', admin.site.urls),
    path('form/',views.teach_form,name="form"),
    path('',include("first_recall.urls")),
    path('special/',views.special,name="special"),
    path('logout/',views.user_logout,name="logout")
]

recall_five/first_recall/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Teacher(models.Model):
    Name=models.CharField(max_length=256)
    Email=models.EmailField(max_length=256)
    Mobile=models.CharField(max_length=20)

    def __str__(self):
        return self.Name;

class  PortfoiloModel(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    portfoilo=models.URLField(max_length=200,blank=True)
    Image_link=models.ImageField(upload_to="profile_pics",blank=True)

    def __str__(self):
        return self.user.username

recall_five/first_recall/forms.py
from django import forms
from django.contrib.auth.models import User
from . import models

class Teacher_Form(forms.ModelForm):

    class Meta:
        model=models.Teacher
        #fields=('Name','Mobile','Email')
        fields='__all__'

class  Userform(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model=User
        fields=('username','email','password')
class Portfoiloform(forms.ModelForm):
    class Meta:
        model=models.PortfoiloModel
        fields=("portfoilo","Image_link")

recall_five/first_recall/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from first_recall.models import Teacher
from django.contrib.auth import authenticate,login,logout
from first_recall.forms import Teacher_Form,Portfoiloform,Userform
from django.urls import reverse
from django.contrib.auth.decorators import login_required
def index(request):
    return HttpResponse("Hello u are at polls Index")
# Create your views here.
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('first_recall:register'))

@login_required
def special(request):
    return HttpResponse("u are logged in, Nice!")

def info(request):
    teacher_data=Teacher.objects.order_by('Name')
    context_data={"Name":teacher_data}
    return render(request,'first_recall\info.html',context=context_data)

def teach_form(request):
    teacher_form=Teacher_Form()
    if request.method=='POST':
        teacher_form= Teacher_Form(request.POST)
        teacher_form.save()
        print("hai")

        if teacher_form.is_valid():
            print("validation success")
            return HttpResponseRedirect("/info/")




    return render(request,"first_recall/teacherform.html",{'teacher_form':teacher_form})

def register(request):
    return render(request,"first_recall/register.html")

def register(request):
    registered=False
    if request.method=="POST":

        user_form=Userform(request.POST)
        profile_form=Portfoiloform(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user=user_form.save()
            # this is for hashing the password
            user.set_password(user.password)
            user.save()

            profile=profile_form.save(commit=False)
            profile.user=user

            if 'Image_link' in request.FILES:
                print("hi")
                profile.Image_link=request.FILES['Image_link']
            profile.save()

            registered=True

        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form=Userform()
        profile_form=Portfoiloform()

    return render(request,"first_recall/register.html",
                                                     {'user_form':user_form,
                                                     'portfoilo_form':profile_form,
                                                     'registered':registered })

def user_login(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')

        user=authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('info'))

            else:
                return HttpResponse('user not active')
        else:
            print("someone tried to login and failed")
            print("username: {} and passeord {}".format(username,password))
            return HttpResponse("Imvalid login details supplied")
    else:
        return render(request,"first_recall/login.html",{})

recall_five/templates/first_recall/base.html
<!DOCTYPE html>

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">


  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <ul class="nav navbar-nav">
        <li><a class="navbar-brand" href="{% url 'info' %}">Info</a></li>
        <li><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
        <li><a class="nav-link" href="{% url 'polls' %}">Polls</a></li>
        <li><a class="nav-link" href="{% url 'form' %}">Form</a></li>
        <li><a class="nav-link" href="{% url 'first_recall:register' %}">Register</a></li>

        {% if user.is_authenticated %}
        <l1><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
        {% else %}
        <li><a class="nav-link" href="{% url "first_recall:user_login" %}">Login</a></li>
        {% endif %}


      </ul>
    </div>
  </nav>
      <div class="container">

        {% block body_block %}
        {% endblock %}
        </div>


  </body>

</html>

recall_five/templates/first_recall/info.html
<!DOCTYPE html>
{% extends "first_recall/base.html" %}
{% block body_block %}
<h1> This is info </h1>
<table border="10px black solid">
  <tr>
  <th>NAme</th>
  <th>Email</th>
  <th>Phone</th>
</tr>
  {% for i in Name %}
  <tr>
<td>{{i.Name | upper}}</td>
<td>  {{i.Email | upper}}</td>
<td> {{i.Mobile}}</td>
</tr>

{% endfor %}
</table>

{% endblock %}

recall_five/templates/first_recall/login.html
{% extends "first_recall/base.html" %}
{% block body_block %}
<div class="jumbotron">
  <h1>please login here</h1>
  <form action="{% url 'first_recall:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Enter username:</label>
    <input type="text" name="username" placeholder="username"><br>

    <label for="password">Enter Password:</label>
    <input type="password" name="password" placeholder="Enter password">

    <input type="submit" value="login">

    </form>
  </div>
{% endblock %}

recall_five/templates/first_recall/register.html
{% extends 'first_recall/base.html' %}
{% block body_block %}
<p>Hola this is registration page</p>
{% if registered %}
 <p>Thanks for Registering<p>
{% else %}
  <div class="jumbotron">
    <form  enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{user_form.as_p}}
      {{portfoilo_form.as_p}}
      <input type="submit" valuue="signup">
    </form>
    </div>
{% endif %}

{% endblock %}

recall_five/templates/first_recall/teacherform.html
{% extends 'first_recall/base.html' %}


{% block body_block %}
<h1> Please fill the form here</h1>
<div class="jumbotron">
 <form  method="post">


{{ teacher_form.as_p }}
{% csrf_token %}
<input type="submit" class="btn btn-primary" value="submit">
 </form>
</div>

{% endblock %}